Update build and release process

diff --git a/.github/workflows/build-test.yaml b/.github/workflows/build-test.yaml
--- a/.github/workflows/build-test.yaml
+++ b/.github/workflows/build-test.yaml
@@ -12,9 +12,6 @@ on:
 permissions:
   contents: read
 
-env:
-  go_version: "^1.19"
-
 jobs:
   test:
     name: "Test [${{ matrix.os }}]"
@@ -32,21 +29,69 @@ jobs:
     steps:
 
     - name: "Checkout"
-      uses: actions/checkout@v3
+      uses: actions/checkout@v5
 
     - name: "Setup Go"
-      uses: actions/setup-go@v3
+      uses: actions/setup-go@v6
       with:
-        go-version: ${{ env.go_version }}
-        cache: true
+        go-version-file: go.mod
+        cache-dependency-path: "**/*.sum"
 
-    - name: "Lint Go code"
-      uses: golangci/golangci-lint-action@v3
-      with:
-        version: latest
+    - name: "Check if `go mod tidy` has been run properly"
+      run: |
+        go mod tidy
+        if ! (git update-index --refresh > /dev/null && git diff-index --quiet HEAD --); then
+          echo 'ERROR: go.mod file is outdated.' >&2
+          echo 'Please update go.mod file by running' >&2
+          echo '    go mod tidy' >&2
+          echo 'in the root of the repository before committing changes.' >&2
+        fi
+
+    - name: "Check if `go mod tidy` has been run properly for tools"
+      run: |
+        (cd tools && go mod tidy)
+        if ! (git update-index --refresh > /dev/null && git diff-index --quiet HEAD --); then
+          echo 'ERROR: Tools go.mod file is outdated.' >&2
+          echo 'Please update tools/go.mod file by running' >&2
+          echo '    (cd tools && go mod tidy)' >&2
+          echo 'in the root of the repository before committing changes.' >&2
+        fi
 
     - name: "Test project"
-      run: go test -timeout 5m ./...
+      run: make test
+
+  lint:
+    name: "Lint [${{ matrix.os }}]"
+
+    strategy:
+      fail-fast: false
+      matrix:
+        os:
+        - ubuntu-latest
+        # - windows-latest # Reenable windows linting when issue with gofmt is resolved
+        - macOS-latest
+
+    runs-on: ${{ matrix.os }}
+
+    steps:
+
+    - name: "Checkout"
+      uses: actions/checkout@v5
+
+    - name: "Setup Go"
+      uses: actions/setup-go@v6
+      with:
+        go-version-file: go.mod
+        cache-dependency-path: "**/*.sum"
+
+    - name: "Lint Go code (action)"
+      uses: golangci/golangci-lint-action@v8
+      with:
+        verify: true
+        version: latest
+
+    - name: "Lint Go code (makefile)"
+      run: make lint
 
   build:
     name: "Build [${{ matrix.GOOS }}/${{ matrix.GOARCH }}]"
@@ -69,13 +114,13 @@ jobs:
     steps:
 
     - name: "Checkout"
-      uses: actions/checkout@v3
+      uses: actions/checkout@v5
 
     - name: "Setup Go"
-      uses: actions/setup-go@v3
+      uses: actions/setup-go@v6
       with:
-        go-version: ${{ env.go_version }}
-        cache: true
+        go-version-file: go.mod
+        cache-dependency-path: "**/*.sum"
 
     - name: "Extract version"
       id: get_version
@@ -95,16 +140,10 @@ jobs:
         echo "GIT_COMMIT=$GIT_COMMIT" >> $GITHUB_ENV
 
     - name: "Build project [${{ matrix.GOOS }}/${{ matrix.GOARCH }}]"
-      run: |
-        mkdir -p dist
-        GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build \
-          -ldflags="-X 'main.Version=$GIT_TAG' -X 'main.Commit=$GIT_COMMIT'" \
-          -o dist/${{ matrix.APP }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }} \
-          -v \
-          .
+      run: make dist/${{ matrix.APP }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
 
     - name: Archive binaries
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v4
       with:
         name: ${{ matrix.APP }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
         path: dist
