Add 'tidy', 'update', 'dist' and 'tools' phony targets in Makefile

diff --git a/.github/workflows/build-test.yaml b/.github/workflows/build-test.yaml
--- a/.github/workflows/build-test.yaml
+++ b/.github/workflows/build-test.yaml
@@ -89,24 +89,14 @@ jobs:
         go-version-file: go.mod
         cache-dependency-path: "**/*.sum"
 
-    - name: "Check if `go mod tidy` has been run properly"
+    - name: "Check if `make tidy` has been run properly"
       run: |
-        go mod tidy
+        make tidy
         if ! (git update-index --refresh > /dev/null && git diff-index --quiet HEAD --); then
-          echo 'ERROR: go.mod file is outdated.' >&2
-          echo 'Please update go.mod file by running' >&2
-          echo '    go mod tidy' >&2
-          echo 'in the root of the repository before committing changes.' >&2
-        fi
-
-    - name: "Check if `go mod tidy` has been run properly for tools"
-      run: |
-        (cd tools && go mod tidy)
-        if ! (git update-index --refresh > /dev/null && git diff-index --quiet HEAD --); then
-          echo 'ERROR: Tools go.mod file is outdated.' >&2
-          echo 'Please update tools/go.mod file by running' >&2
-          echo '    (cd tools && go mod tidy)' >&2
-          echo 'in the root of the repository before committing changes.' >&2
+          echo 'ERROR: One or more go.mod or go.sum files are outdated. >&2
+          echo 'Please update go.mod and go.sum files by running' >&2
+          echo '    make tidy' >&2
+          echo 'before committing changes.' >&2
         fi
 
   build:
